function dF = dF2(in1,in2)
%DF2
%    DF = DF2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    17-Jun-2018 12:37:02

EI = in2(:,1);
alpha = in2(:,5);
k = in2(:,3);
l = in2(:,4);
rhoa = in2(:,2);
z1 = in1(1,:);
z2 = in1(2,:);
t2 = sparse(l.^2);
t3 = sparse(t2.^2);
t4 = sparse(z1-z2);
t5 = sparse(t4.^2);
t6 = sparse(EI.*9.740909103400242e1);
t7 = sparse(k.*t3);
t8 = sparse(rhoa.*t3.*9.740909103400242e1);
t9 = sparse(t6+t7+t8);
t10 = sparse(1.0./t9.^2);
dF = sparse([1,2,1,2],[1,1,2,2],[alpha.*l.*t2.*t3.*t5.*t10.*(-4.383409096530108e2),alpha.*l.*t2.*t3.*t5.*t10.*(-4.383409096530108e2),alpha.*l.*t2.*t3.*t5.*t10.*(-4.383409096530108e2),alpha.*l.*t2.*t3.*t5.*t10.*(-4.383409096530108e2)],2,2);
