function B = B2(r,in2)
%B2
%    B = B2(R,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    17-Jun-2018 12:37:02

EI = in2(:,1);
delta = in2(:,6);
k = in2(:,3);
l = in2(:,4);
rhoa = in2(:,2);
t2 = l.^2;
t3 = t2.^2;
t4 = 1.0./l;
t5 = delta.*t4.*pi;
t6 = sin(t5);
t7 = 2.965820800757861e6;
t8 = 4.13961212179067e7;
t9 = 1.0./delta.^5;
t10 = l.^(9.0./2.0);
t11 = 1.0./pi.^5;
t12 = r.*t4.*pi;
t13 = sin(t12);
t14 = EI.*9.740909103400242e1;
t15 = k.*t3;
t16 = rhoa.*t3.*9.740909103400242e1;
t17 = t14+t15+t16;
t18 = 1.0./sqrt(t17);
t19 = delta.^2;
t20 = pi.^2;
t21 = t6.*t19.*t20;
t22 = cos(t5);
t23 = delta.*l.*t22.*pi.*3.0;
t24 = t21+t23-t2.*t6.*3.0;
B = [t7.*t8.*t9.*t10.*t11.*t13.*t18.*t24.*(-1.70530256582424e-12);t7.*t8.*t9.*t10.*t11.*t13.*t18.*t24.*(-1.70530256582424e-12)];
